version: '3.8'

services:
  backend:
    build:
      context: ./DHBW-Mannheim-WI2023AMB-Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./DHBW-Mannheim-WI2023AMB-Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
